ARG NODE_VERSION=24-alpine

# Etapa 1: Compilación de la aplicación Angular
FROM node:${NODE_VERSION} AS build
ARG BUILD_CONFIGURATION=production

WORKDIR /app

COPY package*.json ./
RUN npm ci --silent

COPY . .
RUN npm run build -- --configuration=${BUILD_CONFIGURATION}

# DIAGNOSTIC PRINT: Print build results to Render logs
RUN echo "=== CONTENTS OF /app/dist ===" && ls -la /app/dist/ && \
    echo "=== SEARCHING FOR index.html ===" && find /app/dist -name "index.html"

# Etapa 2: Servidor Nginx
FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/*

# Copy dist from build stage
COPY --from=build /app/dist /tmp/dist

# Copy static assets and FAIL THE BUILD explicitly if index.html is missing
RUN INDEX_PATH=$(find /tmp/dist -name "index.html" | head -n 1) && \
    if [ -z "$INDEX_PATH" ]; then \
        echo "ERROR: index.html was not generated by Angular build!"; \
        ls -la /tmp/dist; \
        exit 1; \
    fi && \
    TARGET_DIR=$(dirname "$INDEX_PATH") && \
    echo "Found index.html in: $TARGET_DIR" && \
    cp -r "$TARGET_DIR"/* /usr/share/nginx/html/ && \
    rm -rf /tmp/dist

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]